feat(zone.xml): Allow to rate limit 'accept' in rich rules
saltstack-formulas/firewalld-formula pull request #47
Opened 2021-01-13 14:14 UTC by apatard

The current rich_rule macro is supporting to set if the connection
should be accepted or rejected or dropped but doesn't support setting
rate limiting in the 'accept' case. Add code for that.

Signed-off-by: Arnaud Patard <apatard@hupstream.com>

2021-01-14 20:17 UTC, baby-gnu requested changes
Hello @apatard.

Is it possible to modify this PR to test the rate limit on one or two rules?

- modify `pillar.example`
- update the `map.jinja` [verification files](https://github.com/saltstack-formulas/firewalld-formula/tree/master/test/integration/default/files/_mapdata)
- update the `zones_spec.rb`

Regards.

2021-02-05 15:12 UTC, baby-gnu approved these changes
Thanks for the test.

2021-02-05 18:14 UTC, myii approved these changes

2021-02-05 18:14 UTC, merged

2021-02-05 18:15 UTC, myii commented
Appreciate the extra effort, @apatard.  Thanks for the review, @baby-gnu.